# Generated by Django 4.1.4 on 2023-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Profile_picture', models.ImageField(upload_to='')),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.IntegerField(max_length=20)),
                ('Room_Number', models.IntegerField(max_length=100)),
                ('Subjects_taught', models.CharField(max_length=10)),
            ],
        ),
    ]
