# Generated by Django 4.1.4 on 2023-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='Room_Number',
            field=models.IntegerField(),
        ),
    ]
