# Generated by Django 4.1.4 on 2023-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_alter_teacherdetails_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='Profile_picture',
            field=models.ImageField(upload_to='images_dir'),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='Subjects_taught',
            field=models.TextField(),
        ),
    ]
