# Generated by Django 4.1.4 on 2023-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_alter_teacherdetails_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='Phone_Number',
            field=models.CharField(max_length=100),
        ),
    ]
